development:
  clients:
    default:
      database: opentable_development
      hosts:
        - localhost:27017

  options:
    use_utc: true
    use_activesupport_time_zone: true
    raise_not_found_error: false

test:
  clients:
    default:
      database: opentable_test
      hosts:
        - localhost:27017

  options:
    use_utc: true
    use_activesupport_time_zone: true
    raise_not_found_error: false

production:
  clients:
    default:
      database: <%= ENV["MONGO_DB"] %>
      hosts:
        - <%= ENV["MONGO_HOST_AND_PORT"] %>
      options:
        user: <%= ENV["MONGO_USER"] %>
        password: <%= ENV["MONGO_PASSWORD"] %>

  options:
    use_utc: true
    use_activesupport_time_zone: true
    raise_not_found_error: false